"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def get_triangle(n):
    return int(n*(n+1)/2)

def get_pentagonal(n):
    return int(n*(3*n-1)/2)

def get_hexagonal(n):
    return int(n*(2*n-1))

pentagonals = []
hexagonals = []
for i in range(165,100001):
    pentagonals.append(get_pentagonal(i))

for i in range(165,100001):
    hexagonals.append(get_hexagonal(i))

number = 284
while True:
    tr = get_triangle(number)
    if tr > pentagonals[len(pentagonals)-1]:
        print(f'Necesitas mas pentagonals')
        break
    if tr > hexagonals[len(hexagonals)-1]:
        print(f'Necesitas mas hexagonals')
        break
    if tr in pentagonals and tr in hexagonals:
        print(tr)
        break
    number += 1
